name: Gitleaks Secrets Scan for DevOpsWorkshopProject--client master branch

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  check-for-secrets:
    uses: minutuscomputing/DevOps3DEXPIntegration/.github/workflows/DevOps3DEXPIntegration_main.yml@main
    secrets:
      token: ${{ secrets.MY_GITHUB_TOKEN }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE}}